-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 11:52:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema address-R3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema address-R3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `address-R3` DEFAULT CHARACTER SET ucs2 COLLATE ucs2_swedish_ci ;
USE `address-R3` ;

-- -----------------------------------------------------
-- Table `address-R3`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address-R3`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `zip` VARCHAR(20) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address-R3`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address-R3`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_address1_idx` (`address_id` ASC),
  CONSTRAINT `fk_person_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `address-R3`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address-R3`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address-R3`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `registration_plate` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_car_person_idx` (`person_id` ASC),
  CONSTRAINT `fk_car_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `address-R3`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
