-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 11:56:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema syne17
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema syne17
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `syne17` DEFAULT CHARACTER SET utf8mb4 ;
USE `syne17` ;

-- -----------------------------------------------------
-- Table `syne17`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syne17`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `syne17`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syne17`.`person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` INT(11) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `address_id_idx` (`address` ASC),
  INDEX `adress_id_idx` (`address` ASC),
  CONSTRAINT `address_id`
    FOREIGN KEY (`address`)
    REFERENCES `syne17`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `syne17`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `syne17`.`car` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(20) NULL DEFAULT NULL,
  `regnumber` VARCHAR(12) NULL DEFAULT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_idx` (`owner` ASC),
  CONSTRAINT `person_id`
    FOREIGN KEY (`owner`)
    REFERENCES `syne17`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
